export const COURSES = [
  {
    image: require("../../assets/images/image.png"),
    title: "Mastering TypeScript: Advanced Concepts and Design Patterns for Modern Web Development",
    category: "Programming",
    price: 89.99,
    rating: 4.8,
    reviews: 31882,
  },
  {
    image: require("../../assets/images/image.png"),
    title: "Chief Financial Officer Leadership Program: Strategic Financial Management & Decision Making",
    category: "Finance",
    price: 189.99,
    rating: 4.0,
    reviews: 21765,
  },
  {
    image: require("../../assets/images/image.png"),
    title: "Complete Web Design from Figma to Webflow: Master the Modern Design Workflow",
    category: "Design",
    price: 98.00,
    rating: 4.6,
    reviews: 9654,
  },
  {
    image: require("../../assets/images/image.png"),
    title: "Hooked: How to Build Habit-Forming Products and Create Engaging User Experiences",
    category: "Product",
    price: 98.00,
    rating: 4.7,
    reviews: 11021,
  },
  {
    image: require("../../assets/images/image.png"),
    title: "Illustrative Stylings: Professional Lettering and Typography Design with Photoshop",
    category: "Design",
    price: 120.00,
    rating: 4.8,
    reviews: 31882,
  },
  {
    image: require("../../assets/images/image.png"),
    title: "Become a Professional Graphic Designer: From Fundamentals to Advanced Techniques",
    category: "Design",
    price: 149.99,
    rating: 4.5,
    reviews: 15420,
  },
  {
    image: require("../../assets/images/image.png"),
    title: "Advanced Data Visualization: Creating Interactive Dashboards with D3.js and React",
    category: "Development",
    price: 129.99,
    rating: 4.5,
    reviews: 8275,
  },
  {
    image: require("../../assets/images/image.png"),
    title: "Cross-Platform Mobile Development: Building Apps with React Native and Flutter",
    category: "Development",
    price: 139.99,
    rating: 4.6,
    reviews: 12330,
  },
  {
    image: require("../../assets/images/image.png"),
    title: "Enterprise Cybersecurity: Advanced Threat Protection and Incident Response",
    category: "Security",
    price: 199.99,
    rating: 4.7,
    reviews: 9090,
  },
  {
    image: require("../../assets/images/image.png"),
    title: "Agile Project Management: Leading Teams and Delivering Successful Projects",
    category: "Management",
    price: 159.99,
    rating: 4.2,
    reviews: 6060,
  },
];
